#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import subprocess
import os
import sys

snap_list_cmd = "snap list"
snap_list = subprocess.Popen(snap_list_cmd, shell=True, stdout=subprocess.PIPE).stdout
snap_list = [snap_list_element for snap_list_element in snap_list.read().decode().split('\n') if (snap_list_element != None) and (snap_list_element != '') ]
snap_list.pop(0)

snap_programs = []
for package_line in snap_list:
    package_list_args = [arg for arg in package_line.split(' ') if (arg != None) and (arg != '')]
    package_name = package_list_args[0]
    package_note = package_list_args[5]
    package_string = f'{package_name} --{package_note}' if (package_note != '-') else f'{package_name}'
    snap_programs.append(package_string)

print(snap_programs)

# Creates a sample file with install snap list
snap_install_file = open("autogenerated_snap_install_packages.sh", "w")
snap_install_file.write("#!/usr/bin/bash\n\n")
file_instruction = "sudo snap install "
file_instruction += "".join(f'{snap}\n\t\t\t' for snap in snap_programs)
snap_install_file.write(file_instruction)
snap_install_file.close()
